# Generated by Django 5.2.5 on 2026-02-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
