# Generated by Django 5.2.5 on 2026-02-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_alter_planitem_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
