# Generated by Django 5.2.5 on 2026-02-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_incomereport_alter_planitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='planitem',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this plan is active and available for subscription.'),
        ),
    ]
