# Generated by Django 5.2.5 on 2026-02-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_alter_features_order_alter_planitem_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1),
        ),
    ]
