# Generated by Django 5.2.5 on 2026-02-07 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_alter_features_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlanItem',
            new_name='SubscriptionPackage',
        ),
        migrations.RenameField(
            model_name='features',
            old_name='plan_item',
            new_name='subscriptionpackage',
        ),
        migrations.RenameField(
            model_name='paymenthistory',
            old_name='plan_item',
            new_name='subscriptionpackage',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='plan_item',
            new_name='subscriptionpackage',
        ),
    ]
