# Generated by Django 5.2.5 on 2026-02-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0007_rename_planitem_subscriptionpackage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionpackage',
            name='billing_cycle',
            field=models.CharField(blank=True, choices=[('7 Days', '7 Days'), ('14 Days', '14 Days'), ('30 Days', '30 Days')], max_length=20, null=True),
        ),
    ]
